apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: translations-api
  namespace: prod
spec:
  selector:
    matchLabels:
      app: translations-api
  replicas: 1
  template:
    metadata:
      labels:
        app: translations-api
    spec:
      containers:
      - name: translations-api
        image: us.gcr.io/katchplus/translations-api:prod
        imagePullPolicy: Always
        ports:
        - containerPort: 443