apiVersion: v1
kind: Service
metadata:
  name: translations-api-service
  annotations:
    cloud.google.com/app-protocols: '{"translations-sec-port":"HTTPS"}'
  namespace: prod
spec:
  type: NodePort
  selector:
    app: translations-api
  ports:
  - name: translations-sec-port   
    port: 443
    targetPort: 443
    protocol: TCP